#!/usr/bin/python
import os, sys

os.environ['DJANGO_SETTINGS_MODULE'] = 'openfonacide.settings'

try:
    sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'openfonacide'))
    virtenv = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'], 'virtenv')
    virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

    try:
        execfile(virtualenv, dict(__file__=virtualenv))
    except IOError:
        pass
except KeyError:
    pass

from django.core.wsgi import get_wsgi_application

_application = get_wsgi_application()

def application(environ, start_response):
    # pass the WSGI environment variables on through to os.environ
    for key in environ:
        if key.startswith('MEC_'):
            os.environ[key] = environ[key]

    return _application(environ, start_response)


